on:
  push:
    branches:
     - master
  workflow_dispatch:

jobs:
  build:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64 

    - name: Run Makefile
      run: make -f Makefile.windows

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mudclient
        path: |
          mudclient.exe
          SDL2.exe
